version: '3'

volumes:
  db_vol:
    driver: local

services:
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

  vouch:
    image: quay.io/vouch/vouch-proxy
    ports:
      - 9091:9090
    restart: always
    env_file:
      - vouch.env

  nginx:
    image: nginx:stable-alpine
    ports:
      - ${NGINX_PORT}:80
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - phpmyadmin
      - vouch
