version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - db.env
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./data/nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    entrypoint: /cron.sh
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    depends_on:
      - db

  backup:
    image: databack/mysql-backup
    restart: always
    user: "0"
    volumes:
     - ./data/db-backup:/db
    environment:
     - DB_DUMP_TARGET=/db
     - DB_USER=root
     - DB_PASS=${MYSQL_ROOT_PASSWORD}
     - DB_DUMP_FREQ=60
     - DB_SERVER=db
    depends_on:
      - db
