version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zaq12wsx
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    ports:
      - 8083:80
    volumes:
      - ./data/nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    entrypoint: /cron.sh
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - "8084:80"
    expose:
      - "8084"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: zaq12wsx
    restart: always
    depends_on:
      - db

