version: "3.4"

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    cpus: 0.5
    mem_limit: 256M
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-ui:
    container_name: mongo-ui
    image: ugleiton/mongo-gui
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    ports:
      - ${MONGO_UI_PORT}:4321
    environment:
      - MONGO_URL=mongodb://mongo:27017
    cpus: 0.25
    mem_limit: 256M
