version: '3'

volumes:
  db_vol:
    driver: local

services:
  db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

  backup:
    image: databack/mysql-backup
    restart: always
    user: "0"
    volumes:
     - ${DB_BACKUP_DIR}:/db
    environment:
     - DB_DUMP_TARGET=/db
     - DB_USER=root
     - DB_PASS=${MYSQL_ROOT_PASSWORD}
     - DB_DUMP_FREQ=60
     - DB_SERVER=db
    depends_on:
      - db
