name: Mirroring

on:
  push:
    branches:
      - main

jobs:
  to_jihu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@jihulab.com:lwshen/dockerfile.git
          ssh_private_key:
            ${{ secrets.JIHU_SSH_PRIVATE_KEY }}

  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_ACCESS_TOKEN }}@git.vip.cpolar.cn/${{ secrets.GITLAB_USERNAME }}/dockerfile.git